# Generated by Django 4.2.7 on 2023-12-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('r', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EMP',
        ),
    ]
