# Generated by Django 4.2.7 on 2023-12-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitalname', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appq.country')),
            ],
        ),
    ]
